version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd main/app/test
      - npm install
  build:
    commands:
      - node index.js
      - echo Rig Build Completed in Dev Environment